# Generated by Django 3.0.2 on 2020-02-07 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='saved_config',
            field=models.TextField(default='null'),
        ),
    ]
