# Generated by Django 3.0.2 on 2020-01-18 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200118_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedmedia',
            name='log',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='uploadedmedia',
            name='status',
            field=models.NullBooleanField(),
        ),
    ]
