# Generated by Django 3.0.2 on 2020-01-19 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200118_1525'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TelegramDestinationModuleConfig',
            new_name='DestinationModuleConfigTelegram',
        ),
        migrations.AlterField(
            model_name='uploadedmedia',
            name='destination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='media', to='app.Destination'),
        ),
    ]
