# Generated by Django 3.0.2 on 2020-01-19 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20200119_1058'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='destinationmoduleconfigtelegram',
            options={'verbose_name': 'Destination module config Telegram', 'verbose_name_plural': 'Destination module config Telegram'},
        ),
    ]
