# Generated by Django 3.0.2 on 2020-02-03 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_destinationmoduleconfigdiscord_uploader'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='destinationmoduleconfigdiscord',
            options={'verbose_name': 'Destination module config Discord', 'verbose_name_plural': 'Destination module config Discord'},
        ),
        migrations.AddField(
            model_name='destination',
            name='shared',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='destinationmoduleconfigdiscord',
            name='uploader',
            field=models.CharField(choices=[('streamable', 'Streamable (blocked in Russia)'), ('gfycat', 'Gfycat'), ('videobin', 'Videobin')], default='streamable', max_length=32),
        ),
        migrations.CreateModel(
            name='DestinationModuleConfigGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destinations', models.ManyToManyField(to='app.Destination')),
            ],
            options={
                'verbose_name': 'Destination module config Group',
                'verbose_name_plural': 'Destination module config Group',
            },
        ),
    ]
