# Generated by Django 3.0.2 on 2020-04-24 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20200203_0518'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedmedia',
            name='caption',
            field=models.TextField(blank=True, null=True),
        ),
    ]
