# Generated by Django 3.0.2 on 2020-05-06 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_titleentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='titleentry',
            name='custom',
            field=models.BooleanField(default=True),
        ),
    ]
